### ISSUE TITLE
flutter 3.0 breaking changes 

### ISSUE THREAD

**Issue by 94wogus-quantit** [zino-hofmann/graphql-flutter#1131]
in Flutter 3.0 Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

<details>
  <summary>Stacktrace:</summary>

```shell
../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-5.1.0/lib/src/widgets/cache_provider.dart:45:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
```
</details>

**Comment by 94wogus-quantit** [comment]
Currently using the fork repository.

graphql_flutter:
    git:
      url: https://github.com/Quantit-Github/graphql-flutter.git
      path: packages/graphql_flutter
      ref: 93ad28107cd3abfebea0fa85f579c4d60c80cfb1 # commit hash

**Comment by budde377** [comment]
> Currently using the fork repository.
> 
> 
> 
> graphql_flutter:
> 
>     git:
> 
>       url: https://github.com/Quantit-Github/graphql-flutter.git
> 
>       path: packages/graphql_flutter
> 
>       ref: f1ccb2d775826697fa0ab4f6d27d132f8a28f444 # commit hash

Please feel free to submit this as a pr

**Comment by vincenzopalazzo** [comment]
We will track this on https://github.com/zino-hofmann/graphql-flutter/issues/1134

It required some reasoning because if we support the new version we break the API for others that are not able to upgrade now to flutter 3.0

We will find a solution to make all happy! but for sure we will end up in someone that is migrating from flutter 1 to flutter 3 anyway.

**Comment by vincenzopalazzo** [comment]
please @Nzent see the changelog
