### ISSUE TITLE
docs: official documentation site

### ISSUE THREAD

**Issue by manuelduarte077** [zino-hofmann/graphql-flutter#1212]
Description

To create a documentation repository or a web page containing the official documents for the framework.

contributors can work on the issue or to a new feature and also update the docs, and new users can easly understand how it works

Requirements

- [ ] A repository or one branch in the same repo with GHPages
- [ ] https://github.com/zino-hofmann/graphql-flutter/discussions/1210

**Comment by vincenzopalazzo** [comment]
I do not want move the web docs on the because your tool that are introducing need some cofiguration a runtime  with js and react component.

If you want include it inside this repository we should use somethings that generate all a compile time from a md file, such as the rust book tool.

However, I'm in mind to open an organisation  to move some of my tools inside the same umbrella , so as said in the discussion when you have the draft we can move your repository in this umbrella.

I'm closing this because we can continue it on the discussion or in the discord channel :)
