### ISSUE TITLE
Failed to execute 'close' on 'WebSocket'

### ISSUE THREAD

**Issue by zaimanza** [zino-hofmann/graphql-flutter#968]
Hi,
I'm using the graphql subscription and it seems to be passing an error everytime I run my app. 

 The error:
DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1001 is neither.

The subscription works fine and data is passed successfully but I don't know how to close it.

I've found a similar question on stackoverflow. https://stackoverflow.com/questions/69405930/how-to-close-the-websocket-in-graphql-config-flutter

**Comment by jonbhanson** [comment]
This is happening for me as well.  It is triggered in the `_disconnectOnKeepAliveTimeout` method of `SocketClient` when  `event.close()` is called.

**Comment by vincenzopalazzo** [comment]
Hi @jonbhanson,

Do you have some piece of code where we can test to reproduce the problem? thanks.

**Comment by klondikedragon** [comment]
I'm experiencing this as well. In my case, the `GraphQLClient` and `WebSocketLink` lifecycle are managed by a RiverPod provider with autoDispose. The graphQL provider also depends on the auth state, so when the user logs in or logs out it disposes the previous instance and (may) generate a new client (if needed). When all widgets that depend on the GraphQL riverpod provider go away (e.g., user logs out), we are disposing of the websocket, so it doesn't leave a connection open to the server when it's definitely not needed.

On the web platform it looks like the web browser's implementation of websockets only allows certain close codes to be passed by the application. In the case of the gql_websocket_link package, it is now using the `normalClosure` [status](https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/lib/src/link.dart#L379) instead of the `goingAway` [status](https://github.com/zino-hofmann/graphql-flutter/blob/beta/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L300) used by this package's implementation of `WebSocketLink`. Likely it could be solved by using the `normalClosure` status as well.

It seems that the gql_websocket_link also had this problem (https://github.com/gql-dart/gql/issues/260) and they fixed it by changing the status to `goingAway` in https://github.com/gql-dart/gql/pull/278 -- that PR also adjusted the link dispose lifecycle a bit, not sure if their other changes are relevant here also to consider.
